### ISSUE TITLE
User Space access to NX-842 in Linux via VAS?

### ISSUE THREAD

**Issue by plauth** [abalib/power-gzip#3]
Dear Bulent,

in https://github.com/abalib/power-gzip/wiki/NX-842-compression-accelerator, you wrote that the NX-842 is only accessible from Kernel space. Would it be possible to expose the NX-842 to user space analogue to what you did with NX-GZIP?

Could the changes you applied to skiboot and the Linux kernel be "re-used" for the NX-842, or do you expect major differences in exposing the hardware, e.g. as  /dev/crypto/nx-842?

Thank you very much for your feedback :-)

**Comment by abalib** [comment]
> Dear Bulent,
> 
> in https://github.com/abalib/power-gzip/wiki/NX-842-compression-accelerator, you wrote that the NX-842 is only accessible from Kernel space. Would it be possible to expose the NX-842 to user space analogue to what you did with NX-GZIP?
> 
> Could the changes you applied to skiboot and the Linux kernel be "re-used" for the NX-842, or do you expect major differences in exposing the hardware, e.g. as /dev/crypto/nx-842?
> 
> Thank you very much for your feedback :-)

Hi Max 
As far as I know, nx-842 will not be available in the user space.  I am copying @hmyneni who may give us a more authoritative answer.  Thanks.
